spring.application.name=table-management
server.port=8080

# MySQL database connection
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/table_management?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Python@2003}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
