#spring.application.name=reservesmart



# Server
server.port=8080


# JSP View Resolver
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# MySQL Database
#spring.datasource.url=jdbc:mysql://localhost:3306/reservesmart_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.url=jdbc:mysql://localhost:3306/reservesmart?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=admin@1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false


# Gmail SMTP ? Email sending
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sahanchnthuranga@gmail.com
spring.mail.password=hmsw ooqo vsmk obld
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true




## Gmail Email (App Password)
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=YOUR_GMAIL@gmail.com
#spring.mail.password=YOUR_16_CHAR_APP_PASSWORD
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true

#  Twilio SMS (mock mode by default)
twilio.enabled=false
twilio.account.sid=
twilio.auth.token=
twilio.phone.number=

# App Settings
app.name=ReserveSmart
spring.application.name=reservesmart


#Session
server.servlet.session.timeout=30m
